USE [master]
GO

/****** Object:  Database [OrdenCompraTest]    Script Date: 21/03/2021 8:25:57 a. m. ******/
CREATE DATABASE [OrdenCompraTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OrdenCompraTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLDEVLOCAL\MSSQL\DATA\OrdenCompraTest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OrdenCompraTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLDEVLOCAL\MSSQL\DATA\OrdenCompraTest_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OrdenCompraTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OrdenCompraTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OrdenCompraTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OrdenCompraTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OrdenCompraTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OrdenCompraTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [OrdenCompraTest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OrdenCompraTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OrdenCompraTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OrdenCompraTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OrdenCompraTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OrdenCompraTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OrdenCompraTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OrdenCompraTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OrdenCompraTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OrdenCompraTest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OrdenCompraTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OrdenCompraTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OrdenCompraTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OrdenCompraTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OrdenCompraTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OrdenCompraTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OrdenCompraTest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OrdenCompraTest] SET RECOVERY FULL 
GO

ALTER DATABASE [OrdenCompraTest] SET  MULTI_USER 
GO

ALTER DATABASE [OrdenCompraTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OrdenCompraTest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OrdenCompraTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OrdenCompraTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OrdenCompraTest] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OrdenCompraTest] SET QUERY_STORE = OFF
GO

ALTER DATABASE [OrdenCompraTest] SET  READ_WRITE 
GO


